Updated license text for Apollo, added SPDX to headers/source.
LLNL/apollo pull request #14
Opened 2021-07-14 20:48 UTC by cdwdirect

Primary purpose:
- Copyright and license notices updated.
- Followed the example of the Spack repository, per @tgamblin 's suggestion in previous PR.

Additionally:
- Removed outdated / unnecessary files to tidy up the top-level folder.
- Moved SOS+Python tools and examples in the `archive` folder for reference.
- Trailing spaces trimmed out automatically by vim during editing, across numerous files.

2021-07-14 21:56 UTC, tgamblin requested changes
Giorgis should review the technical side of this, but on the license stuff: headers are good, but we can't change the license of Apollo.  It's MIT licensed.

2021-07-14 21:56 UTC, tgamblin commented on COPYRIGHT
> +No copyright assignment is required to contribute to Apollo.
We cannot just switch the license of Apollo from `MIT` to `Apache-2.0 OR MIT`.  It has to stay MIT, unless we want to send it through the process again AND get all contributors' permission, so please change all these `Apache-2.0 OR MIT`'s to `MIT`.

For a single-licensed project, we do't need all this fanciness so also remove `COPYRIGHT`.

2021-07-14 21:56 UTC, tgamblin commented on LICENSE-APACHE
> +                                 Apache License
Remove this file and use a single MIT `LICENSE` file.

2021-07-14 21:56 UTC, tgamblin commented on LICENSE-MIT
> +MIT License
This should just go in a file called `LICENSE`.

2021-07-14 21:56 UTC, tgamblin commented on README.md
> +option.
no - MIT

2021-07-14 21:56 UTC, tgamblin commented on README.md
> +licenses.
Add this sentence here:

> Copyrights and patents in the Apollo project are retained by contributors. No copyright assignment is required to contribute to Apollo.

2021-07-14 21:56 UTC, tgamblin commented on README.md
> +SPDX-License-Identifier: (Apache-2.0 OR MIT)
Just MIT.

2021-07-15 03:47 UTC, cdwdirect commented
> @ggeorgakoudis should review the technical side of this, but on the license stuff: headers are good, but we can't change the license of Apollo. It's MIT licensed.

Thanks for the head's up! I've corrected the license issues you indicated, pushed to `c4b99af` and `499f1b4` commits above.

2022-01-30 09:24 UTC, closed without merging

2022-01-30 09:24 UTC, ggeorgakoudis commented
Superseded by recent development